[workspace]
members = [
    "./bindings/*",
]
exclude = [
    "./bindings/output",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "BSD-3-Clause"
repository = "https://github.com/NTDuck/breadcrumbs"
publish = false

[workspace.dependencies]
# Cross-cutting concerns, centralized

# Crates that we choose to marry
# See: https://blessed.rs/crates

[workspace.lints.rust]
# See: https://doc.rust-lang.org/rustc/lints/listing/index.html

[workspace.lints.clippy]
# See: https://rust-lang.github.io/rust-clippy/master/index.html

[workspace.metadata.rust-analyzer]
# See: https://rust-analyzer.github.io/book/diagnostics.html

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
